import path from 'path';
import { defineConfig } from 'orval';
import dotenv from 'dotenv';

// Load from monorepo root
const rootDir = path.resolve(__dirname, '../..');
dotenv.config({ path: path.join(rootDir, '.env'), override: false });
dotenv.config({ path: path.join(rootDir, '.env.local'), override: true });

export default defineConfig({
    flowclassApi: {
        output: {
            mode: 'tags-split', // Splits the output files by API tags
            target: './src/api/byorval/generated/api',
            client: 'react-query',
            // prettier: true,
            override: {
                header: (info) => [
                    `Generated by orval 🍺`,
                    `Do not edit manually.`,
                    ...(info.title ? [info.title] : []),
                    ...(info.description ? [info.description] : []),
                    ...(info.version ? [`OpenAPI spec version: ${info.version}`] : []),
                ],
                query: {
                    useQuery: true,
                    useInfinite: true,
                },
                mutator: {
                    path: './src/api/byorval/use-custom-instance.ts',
                    name: 'useCustomInstance',
                },
            },
            schemas: './src/api/byorval/generated/model',
            // Generate types for your API responses
            tsconfig: './tsconfig.json',
        },
        input: {
            target: 'http://localhost:3100/api-json',
            validation: false, // Validates the OpenAPI specification
            override: {
                // Only receive js file
                transformer: './src/api/byorval/input-transformer.js',
            },
        },
        // hooks: {
        //     afterAllFilesWrite: {
        //         command: 'prettier --write',
        //         injectGeneratedDirsAndFiles: false,
        //     },
        // },
    },
});