import { getGeminiModel } from "./gemini-client";

export async function performCodeReview(fileContent: string, language: string, fileName: string) {
  const isApiKeyDummy = process.env.GEMINI_API_KEY === "dummy_key" || !process.env.GEMINI_API_KEY;
  if (isApiKeyDummy) {
    // Simulate network delay
    await new Promise(resolve => setTimeout(resolve, 1500));
    return {
      mode: "code-review",
      response: `### AI Code Review for \`${fileName}\` (${language})

#### 🔒 Security Analysis
* **Status**: Pass (No critical vulnerabilities detected)
* **Details**: Input handling seems to be using basic validation. Be sure to sanitize all external parameters before execution or storage to prevent SQL or script injection issues.

#### ⚡ Performance Analysis
* **Time Complexity**: Optimal for current logic.
* **Suggestions**: If processing larger inputs, consider using a memoization cache or utilizing stream-based reads rather than memory buffers.

#### 🛠️ Best Practices & Style
* **Formatting**: Clean and readable.
* **Naming**: Variable and function names are self-documenting.
* **Refactoring**: Consider adding JSDoc/docstring headers to clarify parameters and return types for future maintenance.`,
    };
  }

  try {
    const model = getGeminiModel("gemini-1.5-flash");
    const prompt = `You are a professional software engineer. Perform a code review for the following code file:
Filename: ${fileName}
Language: ${language}

Code:
\`\`\`${language}
${fileContent}
\`\`\`

Analyze the code for:
1. Security vulnerabilities (e.g. injection, data leaks, unsafe operations)
2. Performance optimizations (e.g. time/space complexity improvements)
3. Best practices, formatting, naming conventions, and clean code principles.

Provide the feedback in clear Markdown formatting, structured with headers like Security Analysis, Performance Analysis, and Best Practices.`;

    const result = await model.generateContent(prompt);
    return {
      mode: "code-review",
      response: result.response.text(),
    };
  } catch (error: any) {
    console.error("Gemini Code Review failed, falling back:", error);
    return {
      mode: "code-review",
      response: `### AI Code Review (Fallback)
      
Review could not be fully generated by Gemini API: ${error.message}

Please ensure you write clean, comment-documented, and error-handled code.`,
    };
  }
}

export async function getArchitectureSuggestions(projectContext: string) {
  // Simulate network delay
  await new Promise(resolve => setTimeout(resolve, 1500));
  
  return {
    mode: "architecture",
    response: `### Architecture Suggestions

Based on your project files, here are some architecture suggestions:

1. **Separation of Concerns**: Keep your UI components distinct from your business logic.
2. **State Management**: Consider using a centralized store (like Zustand) if state becomes complex.
3. **API Layer**: Centralize API calls in a dedicated \`lib/api\` or \`services\` directory.`,
  };
}

export async function generateProjectIdeas(problemStatementId?: string, currentIdea?: string) {
  const isApiKeyDummy = process.env.GEMINI_API_KEY === "dummy_key" || !process.env.GEMINI_API_KEY;
  if (isApiKeyDummy) {
    // Simulate network delay
    await new Promise(resolve => setTimeout(resolve, 1500));
    return {
      mode: "idea-gen",
      response: `### AI Suggested Project Ideas

1. **Smart Agriculture Assistant**:
   * *Description*: An automated platform providing real-time moisture monitoring, crop health diagnosis via camera image processing, and climate predictions.
   * *Tech Stack*: Python, React, IoT Sensors, TensorFlow Lite.
   
2. **Decentralized Education Credentialing**:
   * *Description*: Secure, blockchain-backed digital wallet for certificates and diplomas to prevent academic document forgery.
   * *Tech Stack*: Solidity, Next.js, Ethers.js, IPFS.

3. **Intelligent Conversational Counselor**:
   * *Description*: A responsive NLP chatbot that assists students in stress relief, maps study habits, and schedules healthy breaks.
   * *Tech Stack*: Next.js, Python FastAPI, HuggingFace transformers.`,
    };
  }

  try {
    const model = getGeminiModel("gemini-1.5-flash");
    const prompt = `Generate 3 innovative software engineering project ideas based on the student's request or profile. 
${problemStatementId ? `For Problem Statement ID: ${problemStatementId}` : ""}
${currentIdea ? `Inspiration: "${currentIdea}"` : ""}

For each idea, provide:
1. Title
2. Short description (2-3 sentences)
3. Recommended technology stack
Ensure formatting is clean markdown.`;

    const result = await model.generateContent(prompt);
    return {
      mode: "idea-gen",
      response: result.response.text(),
    };
  } catch (error) {
    return {
      mode: "idea-gen",
      response: `### Suggested Ideas
      
1. **IoT Weather Monitor**: A Python-based dashboard for collecting temperature and humidity metrics.
2. **Vocabulary Flashcards**: React app with SQLite that uses spaced repetition to teach coding terms.
3. **Markdown Documentation Hub**: Collaborative edit portal that compiles folders into static docs.`,
    };
  }
}

