export const relations = {
  Institution: [
    'Appointment',
    'ClassEntity',
    'Coupon',
    'Course',
    'InviteMember',
    'RegularPeriods',
    'Media',
    'SettingSocial',
    'SettingWebpageInstitution',
    'StripeConnect',
    'UserRole',
    'RepeatFormats',
    'CommentEntity',
    'SiteGallery',
  ],
  Site: [
    'ClassEntity',
    'Coupon',
    'Course',
    'Institution',
    'InviteMember',
    'RegularPeriods',
    'Media',
    'SettingSocial',
    'SettingSite',
    'SiteGallery',
    'StripeConnect',
    'UserRole',
    'CommentEntity',
  ],

  ClassEntity: ['RegularPeriods'],
  Course: ['ClassEntity', 'RegularPeriods', 'CommentEntity'],
  RegularPeriods: ['PeriodLessons'],
  Appointment: [],
  User: ['Site'],
}
