import { MigrationInterface, QueryRunner } from 'typeorm'

export class AddPackageDiscountsAndFixScheduleSequence1774935604000 implements MigrationInterface {
  name = 'AddPackageDiscountsAndFixScheduleSequence1774935604000'

  public async up(queryRunner: QueryRunner): Promise<void> {
    // 1. Create package_discounts table
    await queryRunner.query(`
      CREATE TABLE "package_discounts" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        "deleted_at" TIMESTAMP WITH TIME ZONE DEFAULT null,
        "created_by" integer,
        "updated_by" integer,
        "site_id" integer NOT NULL,
        "institution_id" integer NOT NULL,
        "name" character varying NOT NULL,
        "amount_per_lesson" numeric NOT NULL,
        "is_all_classes" boolean NOT NULL DEFAULT true,
        "applicable_class_ids" integer[],
        "start_date" timestamp,
        "end_date" timestamp,
        "is_active" boolean NOT NULL DEFAULT true,
        CONSTRAINT "PK_package_discounts" PRIMARY KEY ("id"),
        CONSTRAINT "UQ_package_discounts_name_site_institution" UNIQUE ("name", "site_id", "institution_id")
      )
    `)

    // 2. Fix identity sequences that can get out of sync after data imports
    // For GENERATED BY DEFAULT AS IDENTITY columns, restart the sequence
    // to MAX(id) + 1 to avoid duplicate key errors
    const tables = [
      'class_regular_schedules',
      'class_regular_periods',
      'repeat_formats',
    ]

    for (const table of tables) {
      const result = await queryRunner.query(
        `SELECT COALESCE(MAX(id), 0) + 1 as next_val FROM "${table}"`
      )
      const nextVal = result[0]?.next_val ?? 1
      await queryRunner.query(
        `ALTER TABLE "${table}" ALTER COLUMN id RESTART WITH ${nextVal}`
      )
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "package_discounts"`)
    // Sequence resets cannot be meaningfully reverted
  }
}
