import { MigrationInterface, QueryRunner } from "typeorm";

export class Runs1775741704374 implements MigrationInterface {
    name = 'Runs1775741704374'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."IX_invoices_created_by"`);
        await queryRunner.query(`ALTER TABLE "package_discounts" DROP CONSTRAINT "UQ_package_discounts_name_site_institution"`);
        await queryRunner.query(`ALTER TABLE "invoice_promotion_used" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "invoice_promotion_used" ADD "created_by" integer`);
        await queryRunner.query(`ALTER TABLE "invoice_promotion_used" ADD "updated_by" integer`);
        await queryRunner.query(`ALTER TABLE "invoice_promotion_used" ADD "name" character varying`);
        await queryRunner.query(`ALTER TABLE "invoice_promotion_used" ADD "used_status" character varying DEFAULT 'REDEEMED'`);
        await queryRunner.query(`ALTER TABLE "class_regular_schedules" ALTER COLUMN "period_repeat_format" SET DEFAULT '{"every":1,"unit":"months","startTime":"2026-03-31T15:00:00.000Z"}'`);
        await queryRunner.query(`ALTER TABLE "student_lesson" ALTER COLUMN "expiry_date" SET DEFAULT NOW() + INTERVAL '30 days'`);
        await queryRunner.query(`ALTER TYPE "public"."notification_record_notification_type_enum" RENAME TO "notification_record_notification_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."notification_record_notification_type_enum" AS ENUM('CONFIRM_PAYMENT', 'REJECT_PAYMENT', 'REMINDER', 'APPLICATION', 'FORGET_PASSWORD', 'INVITATION', 'LESSON_POSTPONE', 'ASSIGN_COURSE', 'OTHERS', 'WAITING_FOR_PAYMENT', 'ENROLLED_IN_COURSE', 'RECEIVED_COUPON', 'UPDATE_ON_COURSE_STATUS', 'APPLIED_FOR_COURSE', 'STUDENT_REGISTERED', 'STUDENT_PAID', 'STUDENT_QUESTION', 'STUDENT_ANSWER', 'REQUEST_TIME_CHANGE_APPROVED', 'REQUEST_TIME_CHANGE_REJECTED', 'REQUEST_TIME_CHANGE_PENDING', 'APPLICATION_EMAIL_VERIFICATION', 'TEACHER_FEEDBACK', 'student_lesson_reminder', 'create_invoice')`);
        await queryRunner.query(`ALTER TABLE "notification_record" ALTER COLUMN "notification_type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "notification_record" ALTER COLUMN "notification_type" TYPE "public"."notification_record_notification_type_enum" USING "notification_type"::"text"::"public"."notification_record_notification_type_enum"`);
        await queryRunner.query(`ALTER TABLE "notification_record" ALTER COLUMN "notification_type" SET DEFAULT 'OTHERS'`);
        await queryRunner.query(`DROP TYPE "public"."notification_record_notification_type_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."notification_record_notification_status_enum" RENAME TO "notification_record_notification_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."notification_record_notification_status_enum" AS ENUM('QUEUED', 'SENT', 'DELIVERED', 'OPENED', 'BOUNCED', 'FAILED', 'student_lesson_reminder', 'create_invoice')`);
        await queryRunner.query(`ALTER TABLE "notification_record" ALTER COLUMN "notification_status" TYPE "public"."notification_record_notification_status_enum" USING "notification_status"::"text"::"public"."notification_record_notification_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notification_record_notification_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "invoice_promotion_used" DROP CONSTRAINT "invoice_promotion_used_pkey"`);
        await queryRunner.query(`ALTER TABLE "invoice_promotion_used" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "invoice_promotion_used" ADD "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoice_promotion_used" ADD CONSTRAINT "PK_91772dd04aa3b56e552f569af2e" PRIMARY KEY ("id")`);
        await queryRunner.query(`DROP INDEX "public"."IX_invoice_promotion_used_invoice_id"`);
        await queryRunner.query(`ALTER TABLE "invoice_promotion_used" DROP COLUMN "invoice_id"`);
        await queryRunner.query(`ALTER TABLE "invoice_promotion_used" ADD "invoice_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoice_promotion_used" DROP COLUMN "site_id"`);
        await queryRunner.query(`ALTER TABLE "invoice_promotion_used" ADD "site_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoice_promotion_used" DROP COLUMN "institution_id"`);
        await queryRunner.query(`ALTER TABLE "invoice_promotion_used" ADD "institution_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoice_promotion_used" DROP COLUMN "promotion_type"`);
        await queryRunner.query(`ALTER TABLE "invoice_promotion_used" ADD "promotion_type" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoice_promotion_used" DROP COLUMN "promotion_id"`);
        await queryRunner.query(`ALTER TABLE "invoice_promotion_used" ADD "promotion_id" integer`);
        await queryRunner.query(`ALTER TABLE "invoice_promotion_used" ALTER COLUMN "amount" TYPE numeric`);
        await queryRunner.query(`ALTER TABLE "courses" ALTER COLUMN "email_settings" DROP DEFAULT`);
        await queryRunner.query(`CREATE INDEX "IX_invoice_promotion_used_invoice_id" ON "invoice_promotion_used" ("invoice_id") `);
        await queryRunner.query(`ALTER TABLE "package_discounts" ADD CONSTRAINT "UQ_9fb4dec16ed4e66629cadba1c1c" UNIQUE ("name", "site_id", "institution_id")`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "package_discounts" DROP CONSTRAINT "UQ_9fb4dec16ed4e66629cadba1c1c"`);
        await queryRunner.query(`DROP INDEX "public"."IX_invoice_promotion_used_invoice_id"`);
        await queryRunner.query(`ALTER TABLE "courses" ALTER COLUMN "email_settings" SET DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "invoice_promotion_used" ALTER COLUMN "amount" TYPE numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "invoice_promotion_used" DROP COLUMN "promotion_id"`);
        await queryRunner.query(`ALTER TABLE "invoice_promotion_used" ADD "promotion_id" bigint`);
        await queryRunner.query(`ALTER TABLE "invoice_promotion_used" DROP COLUMN "promotion_type"`);
        await queryRunner.query(`ALTER TABLE "invoice_promotion_used" ADD "promotion_type" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoice_promotion_used" DROP COLUMN "institution_id"`);
        await queryRunner.query(`ALTER TABLE "invoice_promotion_used" ADD "institution_id" bigint NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoice_promotion_used" DROP COLUMN "site_id"`);
        await queryRunner.query(`ALTER TABLE "invoice_promotion_used" ADD "site_id" bigint NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoice_promotion_used" DROP COLUMN "invoice_id"`);
        await queryRunner.query(`ALTER TABLE "invoice_promotion_used" ADD "invoice_id" bigint NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IX_invoice_promotion_used_invoice_id" ON "invoice_promotion_used" ("invoice_id") `);
        await queryRunner.query(`ALTER TABLE "invoice_promotion_used" DROP CONSTRAINT "PK_91772dd04aa3b56e552f569af2e"`);
        await queryRunner.query(`ALTER TABLE "invoice_promotion_used" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "invoice_promotion_used" ADD "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoice_promotion_used" ADD CONSTRAINT "invoice_promotion_used_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`CREATE TYPE "public"."notification_record_notification_status_enum_old" AS ENUM('QUEUED', 'SENT', 'DELIVERED', 'OPENED', 'BOUNCED', 'FAILED', 'admin_notif_after_enrollment_submitted', 'student_notif_after_enrollment_submitted', 'student_notif_after_payment_approved', 'student_notif_after_payment_rejected', 'student_notif_after_add_new_class', 'admin_notif_after_add_new_class', 'student_notif_after_add_new_lesson', 'student_notif_after_change_lesson_date', 'student_notif_payment_reminder', 'student_lesson_reminder', 'create_invoice')`);
        await queryRunner.query(`ALTER TABLE "notification_record" ALTER COLUMN "notification_status" TYPE "public"."notification_record_notification_status_enum_old" USING "notification_status"::"text"::"public"."notification_record_notification_status_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."notification_record_notification_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."notification_record_notification_status_enum_old" RENAME TO "notification_record_notification_status_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."notification_record_notification_type_enum_old" AS ENUM('CONFIRM_PAYMENT', 'REJECT_PAYMENT', 'REMINDER', 'APPLICATION', 'FORGET_PASSWORD', 'INVITATION', 'LESSON_POSTPONE', 'ASSIGN_COURSE', 'OTHERS', 'WAITING_FOR_PAYMENT', 'ENROLLED_IN_COURSE', 'RECEIVED_COUPON', 'UPDATE_ON_COURSE_STATUS', 'APPLIED_FOR_COURSE', 'STUDENT_REGISTERED', 'STUDENT_PAID', 'STUDENT_QUESTION', 'STUDENT_ANSWER', 'REQUEST_TIME_CHANGE_APPROVED', 'REQUEST_TIME_CHANGE_REJECTED', 'REQUEST_TIME_CHANGE_PENDING', 'APPLICATION_EMAIL_VERIFICATION', 'TEACHER_FEEDBACK', 'admin_notif_after_enrollment_submitted', 'student_notif_after_enrollment_submitted', 'student_notif_after_payment_approved', 'student_notif_after_payment_rejected', 'student_notif_after_add_new_class', 'admin_notif_after_add_new_class', 'student_notif_after_add_new_lesson', 'student_notif_after_change_lesson_date', 'student_notif_payment_reminder', 'student_lesson_reminder', 'create_invoice')`);
        await queryRunner.query(`ALTER TABLE "notification_record" ALTER COLUMN "notification_type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "notification_record" ALTER COLUMN "notification_type" TYPE "public"."notification_record_notification_type_enum_old" USING "notification_type"::"text"::"public"."notification_record_notification_type_enum_old"`);
        await queryRunner.query(`ALTER TABLE "notification_record" ALTER COLUMN "notification_type" SET DEFAULT 'OTHERS'`);
        await queryRunner.query(`DROP TYPE "public"."notification_record_notification_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."notification_record_notification_type_enum_old" RENAME TO "notification_record_notification_type_enum"`);
        await queryRunner.query(`ALTER TABLE "student_lesson" ALTER COLUMN "expiry_date" SET DEFAULT (now() + '30 days')`);
        await queryRunner.query(`ALTER TABLE "class_regular_schedules" ALTER COLUMN "period_repeat_format" SET DEFAULT '{"unit": "months", "every": 1, "startTime": "2026-02-28T15:00:00.000Z"}'`);
        await queryRunner.query(`ALTER TABLE "invoice_promotion_used" DROP COLUMN "used_status"`);
        await queryRunner.query(`ALTER TABLE "invoice_promotion_used" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "invoice_promotion_used" DROP COLUMN "updated_by"`);
        await queryRunner.query(`ALTER TABLE "invoice_promotion_used" DROP COLUMN "created_by"`);
        await queryRunner.query(`ALTER TABLE "invoice_promotion_used" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "package_discounts" ADD CONSTRAINT "UQ_package_discounts_name_site_institution" UNIQUE ("site_id", "institution_id", "name")`);
        await queryRunner.query(`CREATE INDEX "IX_invoices_created_by" ON "invoices" ("created_by") `);
    }

}
