import { MigrationInterface, QueryRunner } from 'typeorm'

export class AddInvoicePromotionUsedTable1775100000000
  implements MigrationInterface
{
  name = 'AddInvoicePromotionUsedTable1775100000000'

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "invoice_promotion_used" (
        "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "invoice_id" bigint NOT NULL,
        "site_id" bigint NOT NULL,
        "institution_id" bigint NOT NULL,
        "promotion_type" varchar(50) NOT NULL,
        "promotion_id" bigint NULL,
        "name" varchar(255) NULL,
        "amount" numeric(10,2) NOT NULL DEFAULT 0,
        "used_status" varchar(50) NULL,
        "created_at" timestamptz NOT NULL DEFAULT now(),
        "updated_at" timestamptz NOT NULL DEFAULT now()
      )
    `)
    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS "IX_invoice_promotion_used_invoice_id"
      ON "invoice_promotion_used" ("invoice_id")
    `)
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `DROP INDEX IF EXISTS "IX_invoice_promotion_used_invoice_id"`
    )
    await queryRunner.query(`DROP TABLE IF EXISTS "invoice_promotion_used"`)
  }
}
