@echo off
echo Starting EduSync Python Backend...
if not exist "venv" (
    echo Creating virtual environment...
    python -m venv venv
)
call venv\Scripts\activate.bat
echo Installing requirements...
pip install -r requirements.txt
echo Starting server...
python -m uvicorn main:app --reload --port 8000
