export enum AuthErrorMessage {
  ACCOUNT_NOT_FOUND = 'ACCOUNT_NOT_FOUND',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TEMP_LOGIN_NOT_VALID = 'TEMP_LOGIN_NOT_VALID',
  ID_TOKEN_NOT_VALID = 'ID_TOKEN_NOT_VALID',
  NOT_REGISTERED = 'NOT_REGISTERED',
  CAN_NOT_DELETE = 'CAN_NOT_DELETE',
  TOKEN_DOES_NOT_EXIST = 'TOKEN_DOES_NOT_EXIST',
  CANNOT_SEND_VERIFICATION_EMAIL = 'CANNOT_SEND_VERIFICATION_EMAIL',
}
