export enum InstitutionErrorMessage {
  INSTITUTION_NOT_FOUND = 'INSTITUTION_NOT_FOUND',
  CANNOT_DELETE_CURRENT_USER = 'CANNOT_DELETE_CURRENT_USER',
  GALLERY_NOT_FOUND = 'GALLERY_NOT_FOUND',
  PAYOUT_PREFERENCE_NOT_FOUND = 'PAYOUT_PREFERENCE_NOT_FOUND',
  PAYOUT_PREFERENCE_DEL_FAIL = 'PAYOUT_PREFERENCE_DELETE_FAIL',
}
