export enum InvoiceErrorMessage {
  INVOICE_NOT_FOUND = 'INVOICE_NOT_FOUND',
  ENROLL_COURSE_NOT_FOUND = 'ENROLL_COURSE_NOT_FOUND',
  NO_STUDENT_SCHEDULES_FOUND = 'NO_STUDENT_SCHEDULES_FOUND',
  SEND_CUSTOM_MESSAGES_FAILED = 'SEND_CUSTOM_MESSAGES_FAILED',
}
