export enum openAIErrorMessage {
  MAXIMUM_ATTEMPT_REACHED = 'MAXIMUM_ATTEMPT_REACHED',
  UPDATE_TOKENS_FAILED = 'UPDATE_TOKENS_FAILED',
  CHAT_GPT_FAILED = 'CHAT_GPT_FAILED',
  INCREMENT_MAX_TOKENS_FAILED = 'INCREMENT_MAX_TOKENS_FAILED',
  REQUEST_EMAIL_FAILED = 'REQUEST_EMAIL_FAILED',
  REQUEST_AI_TOKEN_FAILED = 'REQUEST_AI_TOKEN_FAILED',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  INVALID_REQUEST = 'INVALID_REQUEST',
  CONNECTION_TIMEOUT = 'CONNECTION_TIMEOUT',
}
