export enum PaymentEvidenceErrorMessage {
  PAYMENT_EVIDENCE_NOT_FOUND = 'PAYMENT_EVIDENCE_NOT_FOUND',
  PAYMENT_EVIDENCE_ALREADY_ACCEPTED = 'PAYMENT_EVIDENCE_ALREADY_ACCEPTED',
  PAYMENT_EVIDENCE_ALREADY_REJECTED = 'PAYMENT_EVIDENCE_ALREADY_REJECTED',
  PAYMENT_EVIDENCE_ALREADY_PROCESSING = 'PAYMENT_EVIDENCE_ALREADY_PROCESSING',
  INVALID_SEND_ACTION = 'INVALID_SEND_ACTION',
}
