export enum PromotionErrorMessage {
  COUPON_NOT_FOUND = 'COUPON_NOT_FOUND',
  SITE_NOT_FOUND = 'SITE_NOT_FOUND',
  INSTITUTION_NOT_FOUND = 'INSTITUTION_NOT_FOUND',
  INSTITUTION_NOT_BELONG_SITE = 'INSTITUTION_NOT_BELONG_SITE',

  COUPON_NOT_APPLY_FOR_THIS_COURSE = 'COUPON_NOT_APPLY_FOR_THIS_COURSE',
  NOT_ENOUGH_MIN_LESSONS = 'NOT_ENOUGH_MIN_LESSON',
  COUPON_HAS_EXPIRED = 'COUPON_HAS_EXPIRED',
  COUPON_IS_NOT_ACTIVE = 'COUPON_IS_NOT_ACTIVE',
  COUPON_NOT_APPLY_FOR_USER = 'COUPON_NOT_APPLY_FOR_USER',

  COURSE_NOT_BELONG_INSTITUTION = 'COURSE_NOT_BELONG_INSTITUTION',
  COURSE_NOT_FOUND = 'COURSE_NOT_FOUND',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_NOT_BELONG_INSTITUTION = 'USER_NOT_BELONG_INSTITUTION',
  COUPON_ALREADY_EXIST = 'COUPON_ALREADY_EXIST',
  COUPON_USED_UP = 'COUPON_USED_UP',
  BUNDLE_DISCOUNT_NOT_FOUND = 'BUNDLE_DISCOUNT_NOT_FOUND',
  BUNDLE_DISCOUNT_ALREADY_EXIST = 'BUNDLE_DISCOUNT_ALREADY_EXIST',

  PACKAGE_DISCOUNT_NOT_FOUND = 'PACKAGE_DISCOUNT_NOT_FOUND',
  PACKAGE_DISCOUNT_ALREADY_EXIST = 'PACKAGE_DISCOUNT_ALREADY_EXIST',

  TRIAL_LESSON_ALREADY_EXIST = 'TRIAL_LESSON_ALREADY_EXIST',
  TRIAL_LESSON_NOT_FOUND = 'TRIAL_LESSON_NOT_FOUND',
}
