export enum SettingSiteErrorMessage {
  SETTING_SITE_ALREADY_EXISTS = 'SETTING_SITE_ALREADY_EXISTS',
  SETTING_SITE_NOT_FOUND = 'SETTING_SITE_NOT_FOUND',
  SITE_NOT_FOUND = 'SITE_NOT_FOUND',
  COUNTRY_CODE_NOT_FOUND = 'COUNTRY_CODE_NOT_FOUND',
}
