export enum SiteErrorMessage {
  USER_NOT_FOUND_IN_SITE = 'USER_NOT_FOUND_IN_SITE',
  SITE_NOT_FOUND = 'SITE_NOT_FOUND',
  SITE_NAME_ALREADY_USED = 'SITE_NAME_ALREADY_USED',
  SITE_DOMAIN_NAME_ALREADY_USED = 'SITE_DOMAIN_NAME_ALREADY_USED',
  DO_NOT_HAVE_PERMISSION = 'DO_NOT_HAVE_PERMISSION_TO_WORK_ON_SITE_{#1}',
  INSTITUTION_ID_NOT_VALID = 'INSTITUTION_ID_NOT_VALID',
  WHEN_ROLE_IS_SITE_MANAGER_INSTITUTION_ID_MUST_0 = 'WHEN_ROLE_IS_SITE_MANAGER_INSTITUTION_ID_MUST_0',
  SITE_ID_IS_REQUIRED = 'SITE_ID_IS_REQUIRED',
  SITE_INSTITUTION_LIST_FORMAT_ERROR = 'SITE_INSTITUTION_LIST_FORMAT_ERROR',
  CANNOT_INVITE_YOURSELF = 'CANNOT_INVITE_YOURSELF',
}
