export enum UserErrorMessage {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_INVITE_NOT_FOUND = 'USER_INVITE_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_CANNOT_BE_CREATED = 'USER_CANNOT_BE_CREATED',
  NO_PERMISSION = 'NO_PERMISSION',
  ANALYTICS_CANNOT_BE_SENT = 'ANALYTICS_CANNOT_BE_SENT',
  WEB_ANALYTICS_CANNOT_BE_SENT = 'WEB_ANALYTICS_CANNOT_BE_SENT',
  INVALID_PHONE_NUMBER = 'INVALID_PHONE_NUMBER',
  FAILED_TO_CREATE_USER_ALIAS = 'FAILED_TO_CREATE_USER_ALIAS',
  CANNOT_DELETE_SELF = 'CANNOT_DELETE_SELF',
  PHONE_REQUIRED = 'PHONE_REQUIRED',
}

export enum StudentErrorMessage {
  STUDENT_NOT_FOUND = 'STUDENT_NOT_FOUND',
}
