/* eslint-disable react/no-unescaped-entities */
export default () => {
  return (
    <div>
      <ol>
        <li>
          Login to your Flowclass account and navigate to the course or class
          that you want to embed in your website.
        </li>
        <li>
          Click on the "Embed" button or option to generate the code for the{' '}
          <code>&lt;iframe&gt;</code>.
        </li>
        <li>
          Copy the generated code to your clipboard by clicking on the "Copy"
          button or selecting the code and using the keyboard shortcut (Ctrl + C
          on Windows or Command + C on Mac).
        </li>
        <li>
          Open the HTML file of the page where you want to embed the{' '}
          <code>&lt;iframe&gt;</code> in your website.
        </li>
        <li>
          Decide where you want to place the <code>&lt;iframe&gt;</code> and
          insert the code into the HTML file at that location.
        </li>

        <li>
          Copy and paste the iframe code, which should be provided in the code
          generated by Flowclass.
        </li>
        <li>
          Save the changes to your HTML file and refresh your website to see the
          embedded <code>&lt;iframe&gt;</code>.
        </li>
      </ol>
      <p>
        That's it! Your Flowclass course or class should now be embedded and
        visible on your website. Remember to test the embedded{' '}
        <code>&lt;iframe&gt;</code> thoroughly to ensure that it is displaying
        correctly and functioning as expected.
      </p>
    </div>
  )
}
