export interface FeatureInfo {
  id: string
  title: string
  description: string
  videoUrl?: string
  steps: string[]
  tips?: string[]
}

export const getFeatureData = (
  t: (key: string) => string
): Record<string, FeatureInfo> => ({
  'home-description': {
    id: 'home-description',
    title: t('onboarding:featureData.homeDescription.title'),
    description: t('onboarding:featureData.homeDescription.description'),
    videoUrl:
      'https://scribehow.com/embed/How_to_Add_and_Edit_FAQs_on_Flowclass__g3ZISWlVQASJQBgisno0Yg',
    steps: [
      t('onboarding:featureData.homeDescription.steps.0'),
      t('onboarding:featureData.homeDescription.steps.1'),
      t('onboarding:featureData.homeDescription.steps.2'),
      t('onboarding:featureData.homeDescription.steps.3'),
      t('onboarding:featureData.homeDescription.steps.4'),
      t('onboarding:featureData.homeDescription.steps.5'),
    ],
    tips: [
      t('onboarding:featureData.homeDescription.tips.0'),
      t('onboarding:featureData.homeDescription.tips.1'),
      t('onboarding:featureData.homeDescription.tips.2'),
      t('onboarding:featureData.homeDescription.tips.3'),
    ],
  },
  'more-classes': {
    id: 'more-classes',
    title: t('onboarding:featureData.moreClasses.title'),
    description: t('onboarding:featureData.moreClasses.description'),
    videoUrl: 'https://scribehow.com/viewer/Regular_V2__7xh0v5ySSDmzWBdXkpwSog',
    steps: [
      t('onboarding:featureData.moreClasses.steps.0'),
      t('onboarding:featureData.moreClasses.steps.1'),
      t('onboarding:featureData.moreClasses.steps.2'),
      t('onboarding:featureData.moreClasses.steps.3'),
      t('onboarding:featureData.moreClasses.steps.4'),
      t('onboarding:featureData.moreClasses.steps.5'),
    ],
    tips: [
      t('onboarding:featureData.moreClasses.tips.0'),
      t('onboarding:featureData.moreClasses.tips.1'),
      t('onboarding:featureData.moreClasses.tips.2'),
      t('onboarding:featureData.moreClasses.tips.3'),
    ],
  },
  'course-settings': {
    id: 'course-settings',
    title: t('onboarding:featureData.courseSettings.title'),
    description: t('onboarding:featureData.courseSettings.description'),
    steps: [
      t('onboarding:featureData.courseSettings.steps.0'),
      t('onboarding:featureData.courseSettings.steps.1'),
      t('onboarding:featureData.courseSettings.steps.2'),
      t('onboarding:featureData.courseSettings.steps.3'),
      t('onboarding:featureData.courseSettings.steps.4'),
      t('onboarding:featureData.courseSettings.steps.5'),
      t('onboarding:featureData.courseSettings.steps.6'),
    ],
    tips: [
      t('onboarding:featureData.courseSettings.tips.0'),
      t('onboarding:featureData.courseSettings.tips.1'),
      t('onboarding:featureData.courseSettings.tips.2'),
      t('onboarding:featureData.courseSettings.tips.3'),
    ],
  },
  'custom-fields': {
    id: 'custom-fields',
    title: t('onboarding:featureData.customFields.title'),
    description: t('onboarding:featureData.customFields.description'),
    videoUrl:
      'https://scribehow.com/viewer/Creating_Custom_Data_Fields_in_Flowclass__q6BjnwBlTzenVZtGGeILTQ?referrer=documents',
    steps: [
      t('onboarding:featureData.customFields.steps.0'),
      t('onboarding:featureData.customFields.steps.1'),
      t('onboarding:featureData.customFields.steps.2'),
      t('onboarding:featureData.customFields.steps.3'),
      t('onboarding:featureData.customFields.steps.4'),
      t('onboarding:featureData.customFields.steps.5'),
      t('onboarding:featureData.customFields.steps.6'),
    ],
    tips: [
      t('onboarding:featureData.customFields.tips.0'),
      t('onboarding:featureData.customFields.tips.1'),
      t('onboarding:featureData.customFields.tips.2'),
      t('onboarding:featureData.customFields.tips.3'),
    ],
  },
  'custom-forms': {
    id: 'custom-forms',
    title: t('onboarding:featureData.customForms.title'),
    description: t('onboarding:featureData.customForms.description'),
    videoUrl:
      'https://scribehow.com/viewer/Create_a_Membership_Application_Form_and_Class__HQpu7r6oS0K6ir7E8TkpCw?referrer=documents',
    steps: [
      t('onboarding:featureData.customForms.steps.0'),
      t('onboarding:featureData.customForms.steps.1'),
      t('onboarding:featureData.customForms.steps.2'),
      t('onboarding:featureData.customForms.steps.3'),
      t('onboarding:featureData.customForms.steps.4'),
      t('onboarding:featureData.customForms.steps.5'),
      t('onboarding:featureData.customForms.steps.6'),
    ],
    tips: [
      t('onboarding:featureData.customForms.tips.0'),
      t('onboarding:featureData.customForms.tips.1'),
      t('onboarding:featureData.customForms.tips.2'),
      t('onboarding:featureData.customForms.tips.3'),
    ],
  },
  coupons: {
    id: 'coupons',
    title: t('onboarding:featureData.coupons.title'),
    description: t('onboarding:featureData.coupons.description'),
    videoUrl:
      'https://scribehow.com/viewer/Create_a_Custom_Coupon_for_Specific_Students__5JjgojoTThGJc7NhGZKNgA?referrer=documents',
    steps: [
      t('onboarding:featureData.coupons.steps.0'),
      t('onboarding:featureData.coupons.steps.1'),
      t('onboarding:featureData.coupons.steps.2'),
      t('onboarding:featureData.coupons.steps.3'),
      t('onboarding:featureData.coupons.steps.4'),
      t('onboarding:featureData.coupons.steps.5'),
      t('onboarding:featureData.coupons.steps.6'),
    ],
    tips: [
      t('onboarding:featureData.coupons.tips.0'),
      t('onboarding:featureData.coupons.tips.1'),
      t('onboarding:featureData.coupons.tips.2'),
      t('onboarding:featureData.coupons.tips.3'),
    ],
  },
  'online-payment': {
    id: 'online-payment',
    title: t('onboarding:featureData.onlinePayment.title'),
    description: t('onboarding:featureData.onlinePayment.description'),
    steps: [
      t('onboarding:featureData.onlinePayment.steps.0'),
      t('onboarding:featureData.onlinePayment.steps.1'),
      t('onboarding:featureData.onlinePayment.steps.2'),
      t('onboarding:featureData.onlinePayment.steps.3'),
      t('onboarding:featureData.onlinePayment.steps.4'),
      t('onboarding:featureData.onlinePayment.steps.5'),
      t('onboarding:featureData.onlinePayment.steps.6'),
    ],
    tips: [
      t('onboarding:featureData.onlinePayment.tips.0'),
      t('onboarding:featureData.onlinePayment.tips.1'),
      t('onboarding:featureData.onlinePayment.tips.2'),
      t('onboarding:featureData.onlinePayment.tips.3'),
    ],
  },
  'tracking-attendance': {
    id: 'tracking-attendance',
    title: t('onboarding:featureData.trackingAttendance.title'),
    description: t('onboarding:featureData.trackingAttendance.description'),
    steps: [
      t('onboarding:featureData.trackingAttendance.steps.0'),
      t('onboarding:featureData.trackingAttendance.steps.1'),
      t('onboarding:featureData.trackingAttendance.steps.2'),
      t('onboarding:featureData.trackingAttendance.steps.3'),
      t('onboarding:featureData.trackingAttendance.steps.4'),
      t('onboarding:featureData.trackingAttendance.steps.5'),
      t('onboarding:featureData.trackingAttendance.steps.6'),
    ],
    tips: [
      t('onboarding:featureData.trackingAttendance.tips.0'),
      t('onboarding:featureData.trackingAttendance.tips.1'),
      t('onboarding:featureData.trackingAttendance.tips.2'),
      t('onboarding:featureData.trackingAttendance.tips.3'),
    ],
  },
  'adding-class-to-students': {
    id: 'adding-class-to-students',
    title: t('onboarding:featureData.addingClassToStudents.title'),
    description: t('onboarding:featureData.addingClassToStudents.description'),
    videoUrl:
      'https://scribehow.com/viewer/Add_Course_Directly_for_Student__-EksSy8JRg2LRVQe83bo1A?referrer=documents',
    steps: [
      t('onboarding:featureData.addingClassToStudents.steps.0'),
      t('onboarding:featureData.addingClassToStudents.steps.1'),
      t('onboarding:featureData.addingClassToStudents.steps.2'),
      t('onboarding:featureData.addingClassToStudents.steps.3'),
      t('onboarding:featureData.addingClassToStudents.steps.4'),
      t('onboarding:featureData.addingClassToStudents.steps.5'),
      t('onboarding:featureData.addingClassToStudents.steps.6'),
    ],
    tips: [
      t('onboarding:featureData.addingClassToStudents.tips.0'),
      t('onboarding:featureData.addingClassToStudents.tips.1'),
      t('onboarding:featureData.addingClassToStudents.tips.2'),
      t('onboarding:featureData.addingClassToStudents.tips.3'),
    ],
  },
  'import-students': {
    id: 'import-students',
    title: t('onboarding:featureData.importStudents.title'),
    description: t('onboarding:featureData.importStudents.description'),
    steps: [
      t('onboarding:featureData.importStudents.steps.0'),
      t('onboarding:featureData.importStudents.steps.1'),
      t('onboarding:featureData.importStudents.steps.2'),
      t('onboarding:featureData.importStudents.steps.3'),
      t('onboarding:featureData.importStudents.steps.4'),
      t('onboarding:featureData.importStudents.steps.5'),
      t('onboarding:featureData.importStudents.steps.6'),
    ],
    tips: [
      t('onboarding:featureData.importStudents.tips.0'),
      t('onboarding:featureData.importStudents.tips.1'),
      t('onboarding:featureData.importStudents.tips.2'),
      t('onboarding:featureData.importStudents.tips.3'),
    ],
  },
  'invoice-campaign': {
    id: 'invoice-campaign',
    title: t('onboarding:featureData.invoiceCampaign.title'),
    description: t('onboarding:featureData.invoiceCampaign.description'),
    videoUrl:
      'https://scribehow.com/viewer/Assign_Students_Course_by_Create_and_Send_Invoice__XWFdLRoFTH6a7K5qU3Ju4g?referrer=documents',
    steps: [
      t('onboarding:featureData.invoiceCampaign.steps.0'),
      t('onboarding:featureData.invoiceCampaign.steps.1'),
      t('onboarding:featureData.invoiceCampaign.steps.2'),
      t('onboarding:featureData.invoiceCampaign.steps.3'),
      t('onboarding:featureData.invoiceCampaign.steps.4'),
      t('onboarding:featureData.invoiceCampaign.steps.5'),
      t('onboarding:featureData.invoiceCampaign.steps.6'),
    ],
    tips: [
      t('onboarding:featureData.invoiceCampaign.tips.0'),
      t('onboarding:featureData.invoiceCampaign.tips.1'),
      t('onboarding:featureData.invoiceCampaign.tips.2'),
      t('onboarding:featureData.invoiceCampaign.tips.3'),
    ],
  },
  'enter-address': {
    id: 'enter-address',
    title: t('onboarding:featureData.enterAddress.title'),
    description: t('onboarding:featureData.enterAddress.description'),
    steps: [
      t('onboarding:featureData.enterAddress.steps.0'),
      t('onboarding:featureData.enterAddress.steps.1'),
      t('onboarding:featureData.enterAddress.steps.2'),
      t('onboarding:featureData.enterAddress.steps.3'),
      t('onboarding:featureData.enterAddress.steps.4'),
      t('onboarding:featureData.enterAddress.steps.5'),
      t('onboarding:featureData.enterAddress.steps.6'),
    ],
    tips: [
      t('onboarding:featureData.enterAddress.tips.0'),
      t('onboarding:featureData.enterAddress.tips.1'),
      t('onboarding:featureData.enterAddress.tips.2'),
      t('onboarding:featureData.enterAddress.tips.3'),
    ],
  },
  'inviting-instructors': {
    id: 'inviting-instructors',
    title: t('onboarding:featureData.invitingInstructors.title'),
    description: t('onboarding:featureData.invitingInstructors.description'),
    steps: [
      t('onboarding:featureData.invitingInstructors.steps.0'),
      t('onboarding:featureData.invitingInstructors.steps.1'),
      t('onboarding:featureData.invitingInstructors.steps.2'),
      t('onboarding:featureData.invitingInstructors.steps.3'),
      t('onboarding:featureData.invitingInstructors.steps.4'),
      t('onboarding:featureData.invitingInstructors.steps.5'),
      t('onboarding:featureData.invitingInstructors.steps.6'),
    ],
    tips: [
      t('onboarding:featureData.invitingInstructors.tips.0'),
      t('onboarding:featureData.invitingInstructors.tips.1'),
      t('onboarding:featureData.invitingInstructors.tips.2'),
      t('onboarding:featureData.invitingInstructors.tips.3'),
    ],
  },
  'assign-hourly-rate': {
    id: 'assign-hourly-rate',
    title: t('onboarding:featureData.assignHourlyRate.title'),
    description: t('onboarding:featureData.assignHourlyRate.description'),
    videoUrl:
      'https://scribehow.com/viewer/Change_Staff_Hourly_Rates_in_Flowclass__2LYfrGxcQeyqHVL9vEVC7A?referrer=documents',
    steps: [
      t('onboarding:featureData.assignHourlyRate.steps.0'),
      t('onboarding:featureData.assignHourlyRate.steps.1'),
      t('onboarding:featureData.assignHourlyRate.steps.2'),
      t('onboarding:featureData.assignHourlyRate.steps.3'),
      t('onboarding:featureData.assignHourlyRate.steps.4'),
      t('onboarding:featureData.assignHourlyRate.steps.5'),
      t('onboarding:featureData.assignHourlyRate.steps.6'),
    ],
    tips: [
      t('onboarding:featureData.assignHourlyRate.tips.0'),
      t('onboarding:featureData.assignHourlyRate.tips.1'),
      t('onboarding:featureData.assignHourlyRate.tips.2'),
      t('onboarding:featureData.assignHourlyRate.tips.3'),
    ],
  },
  'student-credits': {
    id: 'student-credits',
    title: t('onboarding:featureData.studentCredits.title'),
    description: t('onboarding:featureData.studentCredits.description'),
    videoUrl: 'https://scribehow.com/embed/Add_Credit__wC6X36opTp-WG8voshNxzQ',
    steps: [
      t('onboarding:featureData.studentCredits.steps.0'),
      t('onboarding:featureData.studentCredits.steps.1'),
      t('onboarding:featureData.studentCredits.steps.2'),
      t('onboarding:featureData.studentCredits.steps.3'),
      t('onboarding:featureData.studentCredits.steps.4'),
      t('onboarding:featureData.studentCredits.steps.5'),
      t('onboarding:featureData.studentCredits.steps.6'),
      t('onboarding:featureData.studentCredits.steps.7'),
    ],
    tips: [
      t('onboarding:featureData.studentCredits.tips.0'),
      t('onboarding:featureData.studentCredits.tips.1'),
      t('onboarding:featureData.studentCredits.tips.2'),
      t('onboarding:featureData.studentCredits.tips.3'),
    ],
  },
  'add-locations': {
    id: 'add-locations',
    title: t('onboarding:featureData.addLocations.title'),
    description: t('onboarding:featureData.addLocations.description'),
    steps: [
      t('onboarding:featureData.addLocations.steps.0'),
      t('onboarding:featureData.addLocations.steps.1'),
      t('onboarding:featureData.addLocations.steps.2'),
      t('onboarding:featureData.addLocations.steps.3'),
      t('onboarding:featureData.addLocations.steps.4'),
      t('onboarding:featureData.addLocations.steps.5'),
      t('onboarding:featureData.addLocations.steps.6'),
    ],
    tips: [
      t('onboarding:featureData.addLocations.tips.0'),
      t('onboarding:featureData.addLocations.tips.1'),
      t('onboarding:featureData.addLocations.tips.2'),
      t('onboarding:featureData.addLocations.tips.3'),
    ],
  },
  'approval-requests': {
    id: 'approval-requests',
    title: t('onboarding:featureData.approvalRequests.title'),
    description: t('onboarding:featureData.approvalRequests.description'),
    steps: [
      t('onboarding:featureData.approvalRequests.steps.0'),
      t('onboarding:featureData.approvalRequests.steps.1'),
      t('onboarding:featureData.approvalRequests.steps.2'),
      t('onboarding:featureData.approvalRequests.steps.3'),
      t('onboarding:featureData.approvalRequests.steps.4'),
      t('onboarding:featureData.approvalRequests.steps.5'),
      t('onboarding:featureData.approvalRequests.steps.6'),
    ],
    tips: [
      t('onboarding:featureData.approvalRequests.tips.0'),
      t('onboarding:featureData.approvalRequests.tips.1'),
      t('onboarding:featureData.approvalRequests.tips.2'),
      t('onboarding:featureData.approvalRequests.tips.3'),
    ],
  },
})
