export enum FieldTypes {
  SHORT_ANSWER = 'SHORT_ANSWER',
  PARAGRAPH = 'PARAGRAPH',
  NUMBER = 'NUMBER',
  MULTIPLE_CHOICE = 'MULTIPLE_CHOICE',
  SINGLE_CHOICE = 'SINGLE_CHOICE',
  DROPDOWN_LIST = 'DROPDOWN_LIST',
  SWITCH = 'SWITCH',
  PHONE = 'PHONE',
  DATE = 'DATE',
  EMAIL = 'EMAIL',
  COUNTRY = 'COUNTRY',
  DISPLAY_HEADER = 'HEADING',
  DISPLAY_DESCRIPTION = 'DESCRIPTION',
  IMAGE = 'IMAGE',
  FILE_UPLOAD = 'FILE_UPLOAD',
  STEP_SEPARATOR = 'STEP_SEPARATOR',
}

export const FEATURE_FLAGS = {
  AUTO_FILL: true,
  SHOW_LIST_OF_LESSONS: false,
}
