export const defaultSectionTitle = [
  'COURSE_FEATURES',
  'COURSE_SYLLABUS',
  'COURSE_TARGET',
  'COURSE_INSTRUCTOR',
  'COURSE_STUDENT_PERF',
  'COURSE_APPLICATION',
  'COURSE_ENQUIRY',
  'SCHOOL_ABOUT_US',
  'SCHOOL_FACILITIES',
  'SCHOOL_STUDENT_ACHIEVEMENT',
  'SCHOOL_QUALIFICATION_AWARDS',
  'SCHOOL_SUPPORT',
  'SCHOOL_FAQS',
]

export const courseDefaultSectionTitle = [
  'COURSE_FEATURES',
  'COURSE_SYLLABUS',
  'COURSE_TARGET',
  'COURSE_INSTRUCTOR',
  'COURSE_STUDENT_PERF',
  'COURSE_APPLICATION',
  'COURSE_ENQUIRY',
  'COURSE_TIMETABLE',
]
