export const QUERY_KEY = {
  currentPaymentDetailSchoolKey: 'currentPaymentDetailSchoolKey',
  currentCouponKey: 'currentCouponKey',
  currentBundleDiscountKey: 'currentBundleDiscountKey',
  getAvailableTrialLessonKey: 'getAvailableTrialLessonKey',
  getEnrollmentForm: 'getEnrollmentForm',
  getRecurringClassStartDate: 'getRecurringClassStartDate',
  getAllRecurringLessons: 'getAllRecurringLessons',
  getAllApplicableAdditionalFee: 'getAllApplicableAdditionalFee',
  retrieveStripeSessionStatus: 'retrieveStripeSessionStatus',
  getSchoolStripeConnectionKey: 'getSchoolStripeConnectionKey',
  getStudentPortalSettings: 'getStudentPortalSettings',
  getNotification: 'getNotification',
  getPaymentRecords: 'getPaymentRecords',
  getPastLessons: 'getPastLessons',
  getUpcomingLessons: 'getUpcomingLessons',
  getDetailStudentLesson: 'getDetailStudentLesson',
  getTeachingServiceOpts: 'getTeachingServiceOpts',
}
