export const ErrorMessageCode = {
  STUDENT_ALREADY_EXIST: 'STUDENT_ALREADY_EXIST',
  INVALID_PHONE_NUMBER: 'common:errors.INVALID_PHONE_NUMBER_FOR_USER',
}

export const GoogleErrorMessages = {
  GOOGLE_API_EXPIRED: 'Google API token has expired',
}

export enum ErrorCodes {
  // General errors
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
  INVALID_ACCESS_TOKEN = 'INVALID_ACCESS_TOKEN',
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  INVALID_EMAIL = 'INVALID_EMAIL',
  INVALID_PHONE_NUMBER = 'INVALID_PHONE_NUMBER',
  INVALID_OTP = 'INVALID_OTP',
  INVALID_TOKEN = 'INVALID_TOKEN',
  INVALID_USER = 'INVALID_USER',
  INVALID_CLASS = 'INVALID_CLASS',
  INVALID_COURSE = 'INVALID_COURSE',
  INVALID_SUBSCRIPTION = 'INVALID_SUBSCRIPTION',
  INVALID_PAYMENT = 'INVALID_PAYMENT',
  INVALID_PAYMENT_METHOD = 'INVALID_PAYMENT_METHOD',
  INVALID_PAYMENT_STATUS = 'INVALID_PAYMENT_STATUS',
  INVALID_PAYMENT_TRANSACTION = 'INVALID_PAYMENT_TRANSACTION',
  INVALID_PAYMENT_TRANSACTION_STATUS = 'INVALID_PAYMENT_TRANSACTION_STATUS',
  INVALID_PAYMENT_TRANSACTION_TYPE = 'INVALID_PAYMENT_TRANSACTION_TYPE',
  INVALID_PAYMENT_TRANSACTION_AMOUNT = 'INVALID_PAYMENT_TRANSACTION_AMOUNT',
  INVALID_PAYMENT_TRANSACTION_CURRENCY = 'INVALID_PAYMENT_TRANSACTION_CURRENCY',
  INVALID_PAYMENT_TRANSACTION_DATE = 'INVALID_PAYMENT_TRANSACTION_DATE',

  // Google Integration errors
  AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED',
  CALENDAR_API_ERROR = 'CALENDAR_API_ERROR',
  CALENDAR_CONNECTION_ERROR = 'CALENDAR_CONNECTION_ERROR',
  CALENDAR_EVENT_ERROR = 'CALENDAR_EVENT_ERROR',
  CALENDAR_LIST_ERROR = 'CALENDAR_LIST_ERROR',
  GOOGLE_TOKEN_REFRESH_ERROR = 'GOOGLE_TOKEN_REFRESH_ERROR',
}
