export const enum ThirdPartyIntegrations {
  GOOGLE_CALENDAR = 'GOOGLE_CALENDAR',
  GOOGLE_SHEETS = 'GOOGLE_SHEETS',
  GOOGLE_MEET = 'GOOGLE_MEET',
  GOOGLE_DRIVE = 'GOOGLE_DRIVE',
}

export const enum ContactChannelIntegrations {
  EMAIL = 'EMAIL',
  TWILIO_WHATSAPP = 'TWILIO_WHATSAPP',
  META_WHATSAPP = 'META_WHATSAPP',
  UNOFFICIAL_WHATSAPP = 'UNOFFICIAL_WHATSAPP',
}

export const enum FeatureEnableEnum {
  OWN_BRANDING = 'OWN_BRANDING',
  STUDENT_PORTAL = 'STUDENT_PORTAL',
  RESCHEDULE_REQUEST = 'RESCHEDULE_REQUEST',
  QRCODE_ATTENDANCE = 'QRCODE_ATTENDANCE',
  APPLY_MULTIPLE_COURSES = 'APPLY_MULTIPLE_COURSES',
  CREDIT_SYSTEM = 'CREDIT_SYSTEM',
  TUTOR_CENTRAL = 'TUTOR_CENTRAL',
  INVOICE_CAMPAIGN = 'INVOICE_CAMPAIGN',
  CHANGE_LESSON = 'CHANGE_LESSON',
}
