export const ATOM_KEY = {
  AvailabilityState: 'availabilityState',
  AccountInfo: 'accountInfo',
  DarkMode: 'darkMode',
  LoggedInState: 'loggedIn',
  UserPermissionState: 'userPermissionState',
  SchoolSubscriptionState: 'schoolSubscriptionState',
  UserState: 'userState',
  SchoolState: 'schoolState',
  SiteState: 'siteState',
  CourseState: 'courseState',
  WorkshopState: 'workshopState',
  DisplayLanguageState: 'displayLanguageState',
  StudentState: 'studentState',
  PromotionState: 'promotionState',
  PayoutState: 'payoutState',
  CourseSelectState: 'courseSelectState',
  StudentSelectState: 'StudentSelectState',
  LessonDateTimeState: 'LessonDateTimeState',
  MySchoolState: 'MySchoolState',
  BlockTimeState: 'BlockTimeState',
  InformationFieldState: 'InformationFieldState',
  ApplicationFormState: 'ApplicationFormState',
  AiState: 'aiState',
  NotificationSettingState: 'NotificationSettingState',
  RequiredParamsState: 'RequiredParamsState',
  ClassEditState: 'ClassEditState',
  FullCalendarState: 'FullCalendarState',
  IntegrationCalendarState: 'integrationCalendarState',
  InvoiceStudentState: 'invoiceStudentState',
  CurrentActiveStudentState: 'currentActiveStudentState',
  CurrentActiveParentState: 'currentActiveParentState',
  InvoiceClassState: 'invoiceClassState',
  GroupedStudentsByParents: 'groupedStudentsByParents',
  InvoiceClassSelector: 'invoiceClassSelector',
  InvoiceClassesByTypeSelector: 'invoiceClassesByTypeSelector',
  IsInvoiceExistOnCampaign: 'isInvoiceExistOnCampaignSelector',
  InvoiceSessionState: 'invoiceSessionState',
  AvailableLessonsByClassState: 'availableLessonsByClassState',
  InvoiceSessionsSelector: 'invoiceSessionsSelector',
  InvoiceSessionSelectByIdSelector: 'invoiceSessionSelectByIdSelector',
  InvoiceConfigurationState: 'invoiceConfigurationState',
  InvoiceConfigurationSelector: 'invoiceConfigurationSelector',
  LessonGroupedByStudentSelector: 'lessonGroupedByStudentSelector',
  InvoiceCampaignState: 'invoiceCampaignState',
  AppliedPromotionsState: 'appliedPromotionsState',
  StudentList: 'studentListState',
  ClassesState: 'classesState',
  SendingInvoiceCampaignState: 'sendingInvoiceCampaignState',
  SubscriptionPlansState: 'subscriptionPlansState',
  SubscribedPlansState: 'subscribedPlansState',
  LocationRoomTimeSlotQuotaState: 'LocationRoomTimeSlotQuotaState',
  ClassTimeSlotQuotaState: 'ClassTimeSlotQuotaState',
  UploadProgressState: 'uploadProgressState',
  CurrentUploadProgressState: 'currentUploadProgressState',
} as const

export const SELECTOR_KEY = {
  AppliedPromotionsSelector: 'appliedPromotionsSelector',
  AvailablePlanByPlanIdSelector: 'availablePlanByPlanIdSelector',
  AvailablePlanByPlanTypeSelector: 'availablePlanByPlanTypeSelector',
  ClassesGroupedByStudentSelector: 'classesGroupedByStudentSelector',
  SubscribedPlanByPlanType: 'subscribedPlanByPlanType',
  LocationRoomQuotaByTimeSlotSelector: 'LocationRoomQuotaByTimeSlotSelector',
  ClassQuotaByTimeSlotSelector: 'ClassQuotaByTimeSlotSelector',
  GetInvoiceOfStudentSelector: 'getInvoiceOfStudentSelector',
} as const

export const GENERATOR_KEY = {
  GenerateKeyQuotaTimeSlot: 'GenerateKeyQuotaTimeSlot',
} as const
