export const FEATURE_FLAG = {
  CHECK_CONFLICT_IN_CALENDAR: true,
  ONLY_SHOW_CLASS_WITH_APPLICATION: false,
  ALLOW_ASSIGN_APPOINTMENT_CLASS: false,
  CAN_ASSIGN_MORE_THAN_FIVE_COURSES: false,
  ENABLE_MORE_THAN_ONE_PERIOD_IN_REGULAR_CLASS: true,
  NOTIFICATION_SETTINGS_IN_STUDENT_DETAIL: false,
  RIGHT_TASK_GROUP_SECTION: false,
  ENABLE_MINIMUM_NOTICE_AND_BUFFER_TIME: false,
  SPLIT_INVOICE_FOR_MULTIPLE_STUDENTS: false,
  SHOW_QUOTA_ATTENDANCE_IN_CALENDAR: false,
  REFERRAL_DISCOUNT: false,
  ADD_ENROLLED_CLASS_IN_INVOICE_CAMPAIGN: true,
  SHOW_SAVE_INVOICE_CAMPAIGN_BUTTON: false,
}

export const TRIAL_DAYS_CONSTANT = 14

export const INCOMPLETE_FEATURE_FLAG = {
  ONE_APPLICATION_FOR_MULTIPLE_STUDENTS: false,
  TRANSITIONING_REGULAR_CLASS: true,
  SHOW_STATS_IN_NOTIFICATION_LOG: false,
  INVOICE_CAMPAIGN_ALLOW_RECURRING_SUBSCRIPTION: false,
  SHOW_APPLICATION_PERIOD: false,
}
