export const QUERY_KEY = {
  site: {
    siteDataKey: 'siteDataKey',
    getCurrentSchoolsSiteKey: 'getCurrentSchoolsSiteKey',
    getCurrentSchoolKey: 'getCurrentSchoolKey',
    getMySchoolKey: 'getMySchoolKey',
    getAdminSchoolKey: 'getAdminSchoolKey',
    getDemoSchool: 'getDemoSchool',
  },
  course: {
    getCourseSchoolKey: 'getCourseSchoolKey',
    getCourseKey: 'getCourseKey',
    getWorkshopSchoolKey: 'getWorkshopSchoolKey',
    classListCourseKey: 'classListCourseKey',
    getAllClassesKey: 'getAllClassesKey',
    getDetailClassKey: 'getDetailClassKey',
    studentListCourseKey: 'studentListCourseKey',
    getWorkshopAllSessionsCourseKey: 'getWorkshopAllSessionsCourseKey',
    getCourseAllClassesKey: 'getCourseAllClassesKey',
    listLessonDateTimeKey: 'listLessonDateTimeKey',
    getLessonMatrixKey: 'getLessonMatrixKey',
    getLessonDateTimeKey: 'getLessonDateTimeKey',
    prerequisiteCourseKey: 'prerequisiteCourseKey',
    getEnrolledClassCountKey: 'getEnrolledClassCountKey',
    checkAttendanceModificationsKey: 'checkAttendanceModificationsKey',
    courseAndStudentDataKey: 'courseAndStudentDataKey',
    previewRecurringLessonsKey: 'previewRecurringLessonsKey',
    getTimeSlotClassQuotaKey: 'getTimeSlotClassQuotaKey',
    studentsDataKey: 'studentsDataKey',
    coursesDataKey: 'coursesDataKey',
    hasInvoiceKey: 'hasInvoiceKey',
  },
  settings: {
    getWebpageSettingSchoolKey: 'getWebpageSettingSchoolKey',
    getSettingNotificationsSchoolKey: 'getSettingNotificationsSchoolKey',
    getRegionLanguageSettingSiteKey: 'getRegionLanguageSettingSiteKey',
  },
  appointment: {
    getAppointmentKey: 'getAppointmentKey',
    getAppointmentKeyByClass: 'getAppointmentKeyByClass',
  },
  user: {
    inviteUserKey: 'inviteUserKey',
    getInvitationKey: 'getInvitationKey',
    getInstructorsKey: 'getInstructorsKey',
    getInstructorsWithRatesKey: 'getInstructorsWithRatesKey',
    getInstructorAnalyticsKey: 'getInstructorAnalyticsKey',
    getUpComingClassesKey: 'getUpComingClassesKey',
    getDetailUserKey: 'getDetailUserKey',
    getInstructorRatesKey: 'getInstructorRatesKey',
  },
  plans: {
    planListKey: 'planListKey',
    getPlanAndQuotasKey: 'getPlanAndQuotasKey',
    allPlanPricesKey: 'allPlanPricesKey',
    clientSubscriptionPlans: 'clientSubscriptionPlans',
    allPlanRecordsKey: 'allPlanRecordsKey',
    getSubscriptionDetailSchoolKey: 'getSubscriptionDetailSchoolKey',
    getBillingPortalLinkSchoolKey: 'getBillingPortalLinkSchoolKey',
    getAccountDetailSchoolKey: 'getAccountDetailSchoolKey',
  },
  paymentEvidence: {
    checkPaymentEvidenceKey: 'checkPaymentEvidenceKey',
    previewNextInvoiceKey: 'previewNextInvoiceKey',
  },
  payout: {
    getPayoutMethodsKey: 'getPayoutMethodsKey',
  },
  student: {
    studentSingleInvoiceKey: 'studentSingleInvoiceKey',
    formFieldsKey: 'formFieldsKey',
    studentListKey: 'studentListKey',
    studentListNewKey: 'studentListNewKey',
    studentListBinKey: 'studentListBinKey',
    currentStudentKey: 'currentStudentKey',
    getStudentDetailKey: 'getStudentDetailKey',
    getActivityListKey: 'getActivityListKey',
    studentInvoiceStatisticsKey: 'studentInvoiceStatisticsKey',
    getCurrentStudentQrCodeAttendanceDataKey:
      'getCurrentStudentQrCodeAttendanceDataKey',
    parentAccountKey: 'parentAccountKey',
    getParentAccountDetailKey: 'getParentAccountDetailKey',
    getStudentsByPhoneKey: 'getStudentsByPhoneKey',
    hasCreditRecordsKey: 'hasCreditRecordsKey',
  },
  promotion: {
    getCurrentCouponKey: 'getCurrentCouponKey',
    promotionListCouponKey: 'promotionListCouponKey',
    bundleDiscountsListKey: 'bundleDiscountsListKey',
    getHistoryCouponKey: 'getHistoryCouponKey',
    getStudentCouponKey: 'getStudentCouponKey',
    getAllAdditionalFeeKey: 'getAllAdditionalFeeKey',
    bundleDiscountDetailKey: 'bundleDiscountDetail',
    bundleDiscountStatsKey: 'bundleDiscountStats',
    packageDiscountsListKey: 'packageDiscountsListKey',
    packageDiscountDetailKey: 'packageDiscountDetail',
    packageDiscountsForClassKey: 'packageDiscountsForClass',
  },
  stripe: {
    connectStripeKey: 'connectStripeKey',
    stripeConnectDetailSchoolKey: 'stripeConnectDetailSchoolKey',
  },
  teachingService: {
    getTeachingServiceKey: 'getTeachingServiceKey',
    getTeachingServiceOptsKey: 'getTeachingServiceOptsKey',
    getLessonOptsKey: 'getLessonOptsKey',
    getTeachingServiceByInvoiceIdKey: 'getTeachingServiceByInvoiceIdKey',
  },
  enrollmentForm: {
    getListEnrollmentFormFieldsKey: 'getListEnrollmentFormFieldsKey',
    getEnrollmentFormDetailKey: 'getEnrollmentFormDetailKey',
    getCurrentApplicationFormKey: 'getCurrentApplicationFormKey',
    applicationFormListKey: 'applicationFormListKey',
    studentEnrollmentKey: 'studentEnrollmentKey',
  },
  blockTime: {
    currentBlockTimeKey: 'currentBlockTimeKey',
    blockTimeListKey: 'blockTimeListKey',
  },
  informationField: {
    informationFieldListKey: 'informationFieldListKey',
    getCurrentInformationFieldKey: 'getCurrentInformationFieldKey',
  },
  whatsappTemplate: {
    whatsappTemplatesKey: 'whatsappTemplatesKey',
    detailWhatsappTemplatesKey: 'detailWhatsappTemplatesKey',
  },
  notificationLog: {
    notificationLogsKey: 'notificationLogsKey',
    studentNotificationKey: 'studentNotificationKey',
  },
  studentLesson: {
    getStudentLessonProofTokenKey: 'getStudentLessonProofTokenKey',
    getListStudentLessonKey: 'getListStudentLessonKey',
  },
  trialLesson: {
    fetchTrialLessonsKey: 'fetchTrialLessonsKey',
    fetchTrialSummaryKey: 'fetchTrialSummaryKey',
    fetchDetailTrialLessonsKey: 'fetchDetailTrialLessonsKey',
  },
  userManagement: {
    fetchUsersKey: 'fetchUsersKey',
  },
  rescheduleApproval: {
    getRequestTimeChangeKey: 'getRequestTimeChangeKey',
    getRescheduleSettingsKey: 'getRescheduleSettingsKey',
  },
  locationRoom: {
    getLocationRoomsKey: 'getLocationRoomsKey',
    getLocationGroupAndEquipmentKey: 'getLocationGroupAndEquipmentKey',
    getLocationRoomKey: 'getLocationRoomKey',
    getLocationRoomWithTimeSlotQuotaKey: 'getLocationRoomWithTimeSlotQuotaKey',
  },
  availability: {
    fetchAvailabilitiesKey: 'fetchAvailabilitiesKey',
    fetchCurrentAvailabilityKey: 'fetchCurrentAvailabilityKey',
    fetchIntegrationCalendarsKey: 'fetchIntegrationCalendarsKey',
  },
  integrations: {
    fetchOnlineMeetingConnectionsKey: 'fetchOnlineMeetingConnectionsKey',
    fetchAllCalendarEventsKey: 'fetchAllCalendarEventsKey',
    fetchCalendarEventKey: 'fetchCalendarEventKey',
    fetchMeetingsKey: 'fetchMeetingsKey',
    fetchMeetingKey: 'fetchMeetingKey',
  },
  googleIntegration: {
    baseKey: 'googleIntegration',
    sheetStatusKey: ['googleIntegration', 'sheets', 'status'],
    driveFoldersKey: ['googleIntegration', 'sheets', 'driveFolders'],
    calendarConnectionsKey: ['googleIntegration', 'calendar', 'connections'],
    calendarListKey: ['googleIntegration', 'calendar', 'list'],
    calendarEventsKey: ['googleIntegration', 'calendar', 'events'],
    meetConnectionsKey: ['googleIntegration', 'meet', 'connections'],
    meetEventsKey: ['googleIntegration', 'meet', 'events'],
    meetSpaceKey: ['googleIntegration', 'meet', 'space'],
    meetTokenKey: ['googleIntegration', 'meet', 'token'],
    driveStatusKey: ['googleIntegration', 'drive', 'status'],
    driveFilesKey: ['googleIntegration', 'drive', 'files'],
    driveFileKey: ['googleIntegration', 'drive', 'file'],
    driveCreateFolderKey: ['googleIntegration', 'drive', 'createFolder'],
    driveSetRootFolderKey: ['googleIntegration', 'drive', 'setRootFolder'],
    driveUploadKey: ['googleIntegration', 'drive', 'upload'],
    driveDownloadByUrlKey: ['googleIntegration', 'drive', 'downloadByUrl'],
    driveSearchKey: ['googleIntegration', 'drive', 'search'],
    driveDeleteFileKey: ['googleIntegration', 'drive', 'deleteFile'],
    driveQuotaKey: ['googleIntegration', 'drive', 'quota'],
    getAuthUrlKey: 'getAuthUrlKey',
    disconnectIntegrationKey: 'disconnectIntegrationKey',
  },
  customMessage: {
    customMessageDataKey: 'customMessageDataKey',
    customMessagePreparedDataKey: 'customMessagePreparedDataKey',
  },
  classRegularSchedule: {
    getAll: 'classRegularSchedule.getAll',
    getByClassId: 'classRegularSchedule.getByClassId',
    getById: 'classRegularSchedule.getById',
  },
  studentInvoice: {
    getAllStudents: 'getAllStudentsKey',
    getCouponAndBundle: 'getCouponAndBundleKey',
  },
  sitesFeatureEnabled: {
    getAllSitesFeatureEnabled: 'getAllSitesFeatureEnabledKey',
  },
  classMaterials: {
    getListClassMaterialsKey: 'getListClassMaterialsKey',
  },
  studentSubmission: {
    getListStudentSubmissionKey: 'getListStudentSubmissionKey',
    getListStudentSubmissionByLessonKey: 'getListStudentSubmissionByLessonKey',
  },
  statistics: {
    overview: 'getStatisticsOverviewKey',
    byCourse: 'getStatisticsByCourseKey',
    byClass: 'getStatisticsByClassKey',
    byInstructor: 'getStatisticsByInstructorKey',
    studentOverview: 'getStatisticsStudentOverviewKey',
    byStudent: 'getStatisticsByStudentKey',
    dynamic: 'getStatisticsDynamicKey',
    lessonList: 'statistics-lesson-list',
    lessonDetail: 'statistics-lesson-detail',
    dropoutStudents: 'statistics-dropout-students',
  },
}

export const PARAMS_KEY = {
  SITE_ID: 'siteId',
  INSTITUTION_ID: 'institutionId',
  COURSE_ID: 'courseId',
  CLASS_ID: 'classId',
  ENROL_ID: 'enrolId',
  WORKSHOP_SESSION_ID: 'workshopSessionId',
  LESSON_ID: 'lessonId',
  WORKSHOP_ID: 'workshopId',
  COUPON_ID: 'couponId',
  SETTING_SITE_ID: 'settingSiteId',
  REQUEST_PAYOUT_ID: 'requestPayoutId',
  SETTING_SOCIAL_ID: 'settingSocialId',
  SETTING_NOTIFICATIONS_ID: 'settingNotificationsId',
  SETTING_WEBPAGE_INSTITUTION_ID: 'settingWebpageInstitutionId',
  SEO_SETTING_ID: 'seoSettingId',
  COMMENT_ID: 'commentId',
  APPOINTMENT_ID: 'appointmentId',
  TOKEN: 'token',
  BUNDLE_ID: 'bundleId',
}
