export enum FeatureEnableEnum {
  OWN_BRANDING = 'OWN_BRANDING',
  STUDENT_PORTAL = 'STUDENT_PORTAL',
  RESCHEDULE_REQUEST = 'RESCHEDULE_REQUEST',
  QRCODE_ATTENDANCE = 'QRCODE_ATTENDANCE',
  APPLY_MULTIPLE_COURSES = 'APPLY_MULTIPLE_COURSES',
  CREDIT_SYSTEM = 'CREDIT_SYSTEM',
  TUTOR_CENTRAL = 'TUTOR_CENTRAL',
  TEXT_VERSION = 'TEXT_VERSION',
}
