export enum RecordLogType {
  ASSIGN_COUPON_FOR_STUDENT = 'ASSIGN_COUPON_FOR_STUDENT',
  CREATE_COUPON = 'CREATE_COUPON',
  USAGE_COUPON = 'USAGE_COUPON',
  CONFIRM_USAGE_COUPON = 'CONFIRM_USAGE_COUPON',
  DELETE_COUPON = 'DELETE_COUPON',
  INACTIVE_COUPON = 'INACTIVE_COUPON',
  STUDENT_CHANGE_INFORMATION = 'STUDENT_CHANGE_INFORMATION',
  STUDENT_ADD_CLASS = 'STUDENT_ADD_CLASS',
  STUDENT_CHANGE_TIME_TABLE = 'STUDENT_CHANGE_TIME_TABLE',
  ADDING_CLASS = 'ADDING_CLASS',
  RESCHEDULE_LESSON = 'RESCHEDULE_LESSON',
}

export type StudentActivityType = {
  id: number
  type: RecordLogType
  detail: Record<string, any>
}
