import { MigrationInterface, QueryRunner } from 'typeorm'

export class AddDivitTables1748000000000 implements MigrationInterface {
  name = 'AddDivitTables1748000000000'

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE "divit_configs" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "created_at" timestamptz NOT NULL DEFAULT now(),
        "updated_at" timestamptz NOT NULL DEFAULT now(),
        "deleted_at" timestamptz DEFAULT NULL,
        "created_by" integer DEFAULT NULL,
        "updated_by" integer DEFAULT NULL,
        "site_id" integer NOT NULL,
        "institution_id" integer NOT NULL,
        "api_key_encrypted" character varying DEFAULT NULL,
        "signature_key_encrypted" character varying DEFAULT NULL,
        "environment" character varying NOT NULL DEFAULT 'sandbox',
        "enabled" boolean NOT NULL DEFAULT false,
        CONSTRAINT "UQ_divit_configs_institution_id" UNIQUE ("institution_id")
      )
    `)

    await queryRunner.query(
      `CREATE INDEX "IX_divit_configs_site_id" ON "divit_configs" ("site_id")`
    )
    await queryRunner.query(
      `CREATE INDEX "IX_divit_configs_institution_id" ON "divit_configs" ("institution_id")`
    )

    await queryRunner.query(`
      CREATE TABLE "divit_orders" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "created_at" timestamptz NOT NULL DEFAULT now(),
        "updated_at" timestamptz NOT NULL DEFAULT now(),
        "deleted_at" timestamptz DEFAULT NULL,
        "created_by" integer DEFAULT NULL,
        "updated_by" integer DEFAULT NULL,
        "site_id" integer NOT NULL,
        "institution_id" integer NOT NULL,
        "invoice_id" integer NOT NULL,
        "divit_order_id" character varying DEFAULT NULL,
        "divit_order_token" character varying DEFAULT NULL,
        "redirect_url" character varying DEFAULT NULL,
        "status" character varying NOT NULL DEFAULT 'pending',
        "environment" character varying NOT NULL DEFAULT 'sandbox'
      )
    `)

    await queryRunner.query(
      `CREATE INDEX "IX_divit_orders_site_id" ON "divit_orders" ("site_id")`
    )
    await queryRunner.query(
      `CREATE INDEX "IX_divit_orders_institution_id" ON "divit_orders" ("institution_id")`
    )
    await queryRunner.query(
      `CREATE INDEX "IX_divit_orders_invoice_id" ON "divit_orders" ("invoice_id")`
    )
    await queryRunner.query(
      `CREATE INDEX "IX_divit_orders_divit_order_id" ON "divit_orders" ("divit_order_id")`
    )
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE IF EXISTS "divit_orders"`)
    await queryRunner.query(`DROP TABLE IF EXISTS "divit_configs"`)
  }
}
